-- Sync tools that exist in code but were not seeded into ai_tools yet.

INSERT INTO ai_tools (
    name,
    type,
    description,
    sql_template,
    accuracy_percentage,
    is_active,
    allowed_roles,
    required_fields
)
VALUES
    ('add_student_to_class', 'SQL_TEMPLATE', 'Them sinh vien vao lop', 'INSERT INTO enrollments (student_id, class_name, created_at, updated_at) SELECT u.id, %s, NOW(), NOW() FROM users u WHERE u.code = %s ON CONFLICT DO NOTHING RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'class_name,student_code'),
    ('create_academic_request', 'BACKEND_ACTION', 'Tao don hoc vu', NULL, NULL, TRUE, 'STUDENT', 'request_type,reason'),
    ('create_group_chat', 'BACKEND_ACTION', 'Tao nhom chat lop', NULL, NULL, TRUE, 'LECTURER', 'class_name'),
    ('delete_course', 'SQL_TEMPLATE', 'Xoa mem mon hoc', 'UPDATE courses SET status=''INACTIVE'', updated_at=NOW() WHERE code=%s OR unaccent(name) ILIKE unaccent(%s) RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'code,name'),
    ('delete_major', 'SQL_TEMPLATE', 'Xoa mem nganh hoc', 'UPDATE majors SET status=''INACTIVE'', updated_at=NOW() WHERE code=%s OR unaccent(name) ILIKE unaccent(%s) RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'code,name'),
    ('delete_specialization', 'SQL_TEMPLATE', 'Xoa mem chuyen nganh', 'UPDATE specializations SET status=''INACTIVE'', updated_at=NOW() WHERE code=%s OR unaccent(name) ILIKE unaccent(%s) RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'code,name'),
    ('delete_sub_specialization', 'SQL_TEMPLATE', 'Xoa chuyen nganh hep', 'DELETE FROM sub_specializations WHERE code=%s OR unaccent(name) ILIKE unaccent(%s) RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'code,name'),
    ('get_courses_by_semester', 'SQL_TEMPLATE', 'Danh sach mon hoc theo hoc ky', 'SELECT c.code, c.name, c.credits, c.status, sem.code AS semester_code, sem.name AS semester_name, COUNT(DISTINCT cs.class_name) AS total_classes, COUNT(DISTINCT e.student_id) AS total_students FROM courses c JOIN class_sections cs ON c.id = cs.course_id JOIN semesters sem ON cs.semester_id = sem.id LEFT JOIN enrollments e ON cs.class_name = e.class_name WHERE unaccent(COALESCE(sem.code, '''')) ILIKE unaccent(%s) OR unaccent(COALESCE(sem.name, '''')) ILIKE unaccent(%s) OR unaccent(COALESCE(sem.code, '''')) = unaccent(%s) GROUP BY c.code, c.name, c.credits, c.status, sem.code, sem.name ORDER BY c.name', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF,LECTURER,STUDENT', 'semester_code,semester_name,semester'),
    ('get_lecturer_schedule_by_search', 'SQL_TEMPLATE', 'Lich giang day cua giang vien theo ma/ten', 'SELECT ts.date, ts.slot_number, cs.class_name, c.name AS course_name, c.credits, r.name AS room, r.capacity AS room_capacity, st.start_time, st.end_time, u.full_name AS lecturer_name, sem.name AS semester FROM timetable_slots ts JOIN class_sections cs ON ts.class_name = cs.class_name JOIN courses c ON cs.course_id = c.id JOIN users u ON cs.lecturer_id = u.id LEFT JOIN semesters sem ON cs.semester_id = sem.id LEFT JOIN rooms r ON ts.room_id = r.id LEFT JOIN slot_types st ON ts.slot_type_id = st.id WHERE (%s = '''' OR u.code = %s) AND (%s = '''' OR unaccent(u.full_name) ILIKE unaccent(%s)) AND (%s <> '''' OR %s <> '''') AND ts.date BETWEEN %s AND %s ORDER BY ts.date, ts.slot_number', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'lecturer_code,full_name,date'),
    ('get_major_id_by_name', 'SQL_TEMPLATE', 'Tra cuu ma nganh theo ten', 'SELECT id, name, code FROM majors WHERE (unaccent(name) ILIKE unaccent(%s) OR unaccent(code) ILIKE unaccent(%s)) AND status = ''ACTIVE'' LIMIT 1', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'major_name,major_code'),
    ('get_my_courses', 'SQL_TEMPLATE', 'Danh sach mon hoc cua sinh vien hien tai', 'SELECT DISTINCT c.name AS course_name, c.code AS course_code, c.credits, cs.class_name, u_lec.full_name AS lecturer_name, sem.name AS semester, sem.code AS semester_code, sem.start_date FROM enrollments e JOIN class_sections cs ON e.class_name = cs.class_name JOIN courses c ON cs.course_id = c.id JOIN semesters sem ON cs.semester_id = sem.id LEFT JOIN users u_lec ON cs.lecturer_id = u_lec.id WHERE e.student_id = %s ORDER BY sem.start_date DESC, c.name', NULL, TRUE, 'STUDENT', NULL),
    ('get_my_grades', 'SQL_TEMPLATE', 'Bang diem chi tiet cua nguoi dung hien tai', 'SELECT c.name AS course_name, c.code AS course_code, c.credits, cs.class_name, sem.name AS semester, gc.name AS component, gc.type AS component_type, gc.weight, sg.score, sg.attempt, ROUND(sg.score * gc.weight / 100.0, 2) AS weighted_score FROM student_grades sg JOIN enrollments e ON sg.enrollment_id = e.id JOIN grade_components gc ON sg.grade_component_id = gc.id JOIN courses c ON gc.course_id = c.id JOIN class_sections cs ON e.class_name = cs.class_name JOIN semesters sem ON cs.semester_id = sem.id WHERE e.student_id = %s ORDER BY sem.start_date DESC, c.name, gc.weight DESC', NULL, TRUE, 'STUDENT', NULL),
    ('get_my_schedule', 'SQL_TEMPLATE', 'Thoi khoa bieu tong quat cua nguoi dung hien tai', 'SELECT DISTINCT ts.date, ts.slot_number, cs.class_name, c.name AS course_name, c.credits, r.name AS room, r.capacity AS room_capacity, st.start_time, st.end_time, ts.status AS slot_status FROM timetable_slots ts JOIN class_sections cs ON ts.class_name = cs.class_name JOIN courses c ON cs.course_id = c.id LEFT JOIN rooms r ON ts.room_id = r.id LEFT JOIN slot_types st ON ts.slot_type_id = st.id LEFT JOIN enrollments e ON cs.class_name = e.class_name WHERE (e.student_id = %s OR cs.lecturer_id = %s) AND ts.date >= CURRENT_DATE ORDER BY ts.date, ts.slot_number', NULL, TRUE, 'LECTURER,STUDENT', NULL),
    ('get_my_schedule_targeted', 'SQL_TEMPLATE', 'Thoi khoa bieu theo khoang ngay cua nguoi dung hien tai', 'SELECT DISTINCT ts.date, ts.slot_number, cs.class_name, c.name AS course_name, c.credits, r.name AS room, r.capacity AS room_capacity, st.start_time, st.end_time, ts.status AS slot_status, sem.name AS semester FROM timetable_slots ts JOIN class_sections cs ON ts.class_name = cs.class_name JOIN courses c ON cs.course_id = c.id JOIN semesters sem ON cs.semester_id = sem.id LEFT JOIN rooms r ON ts.room_id = r.id LEFT JOIN slot_types st ON ts.slot_type_id = st.id LEFT JOIN enrollments e ON cs.class_name = e.class_name WHERE (e.student_id = %s OR cs.lecturer_id = %s) AND (ts.date BETWEEN %s AND %s) AND (unaccent(cs.class_name) ILIKE unaccent(%s) OR %s = '''') ORDER BY ts.date, ts.slot_number', NULL, TRUE, 'LECTURER,STUDENT', NULL),
    ('get_specialization_id_by_name', 'SQL_TEMPLATE', 'Tra cuu ma chuyen nganh theo ten', 'SELECT id, name, code FROM specializations WHERE (unaccent(name) ILIKE unaccent(%s) OR unaccent(code) ILIKE unaccent(%s)) AND status = ''ACTIVE'' LIMIT 1', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'specialization_name,specialization_code'),
    ('get_student_schedule_by_search', 'SQL_TEMPLATE', 'Lich hoc cua sinh vien theo ma/ten', 'SELECT ts.date, ts.slot_number, cs.class_name, c.name AS course_name, c.credits, r.name AS room, st.start_time, st.end_time, u.full_name AS student_name, u.code AS student_code, sem.name AS semester FROM timetable_slots ts JOIN class_sections cs ON ts.class_name = cs.class_name JOIN enrollments e ON cs.class_name = e.class_name JOIN users u ON e.student_id = u.id JOIN courses c ON cs.course_id = c.id LEFT JOIN semesters sem ON cs.semester_id = sem.id LEFT JOIN rooms r ON ts.room_id = r.id LEFT JOIN slot_types st ON ts.slot_type_id = st.id WHERE (%s = '''' OR u.code = %s) AND (%s = '''' OR unaccent(u.full_name) ILIKE unaccent(%s)) AND (%s <> '''' OR %s <> '''') AND ts.date BETWEEN %s AND %s ORDER BY ts.date, ts.slot_number', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'student_code,full_name,date'),
    ('get_students_without_class', 'SQL_TEMPLATE', 'Danh sach sinh vien chua duoc xep lop', 'SELECT u.full_name, u.code, u.email, COALESCE(m.name, '''') AS major, COALESCE(sp.gpa, 0) AS gpa FROM users u LEFT JOIN student_profiles sp ON u.id = sp.user_id LEFT JOIN majors m ON sp.major_id = m.id WHERE u.role = ''STUDENT'' AND u.status = ''ACTIVE'' AND u.id NOT IN (SELECT DISTINCT student_id FROM enrollments) ORDER BY u.full_name', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', NULL),
    ('get_top_students', 'SQL_TEMPLATE', 'Danh sach sinh vien co ket qua cao nhat', 'SELECT u.full_name, u.code, u.email, COALESCE(sp.gpa, 0) AS gpa, COALESCE(m.name, '''') AS major, COALESCE(s.name, '''') AS specialization, (SELECT COUNT(*) FROM enrollments e WHERE e.student_id = u.id) AS classes_enrolled FROM users u JOIN student_profiles sp ON u.id = sp.user_id LEFT JOIN majors m ON sp.major_id = m.id LEFT JOIN specializations s ON sp.specialization_id = s.id WHERE u.status = ''ACTIVE'' AND u.role = ''STUDENT'' ORDER BY sp.gpa DESC NULLS LAST LIMIT 20', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', NULL),
    ('remove_student_from_class', 'SQL_TEMPLATE', 'Go sinh vien khoi lop', 'DELETE FROM enrollments WHERE class_name = %s AND student_id = (SELECT id FROM users WHERE code = %s LIMIT 1) RETURNING id', NULL, TRUE, 'ADMIN,ACADEMIC_STAFF', 'class_name,student_code')
ON CONFLICT (name) DO UPDATE
SET
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    sql_template = EXCLUDED.sql_template,
    is_active = EXCLUDED.is_active,
    allowed_roles = EXCLUDED.allowed_roles,
    required_fields = EXCLUDED.required_fields,
    updated_at = NOW();
