UPDATE ai_tools
SET type = 'BACKEND_ACTION'
WHERE name IN (
    'create_notification',
    'send_email',
    'create_user',
    'update_user',
    'delete_user',
    'create_course',
    'update_course',
    'create_major',
    'update_major',
    'create_specialization',
    'create_room',
    'create_semester',
    'create_sub_specialization',
    'create_class',
    'create_group_chat',
    'create_academic_request',
    'assign_course_to_specialization',
    'assign_course_to_sub_specialization',
    'add_student_to_class',
    'remove_student_from_class',
    'delete_course',
    'delete_major',
    'delete_room',
    'delete_semester',
    'delete_specialization',
    'delete_sub_specialization',
    'delete_class',
    'approve_schedule_request',
    'reject_schedule_request',
    'import_component_grades',
    'export_attendance_stats',
    'export_excel'
);
